swagger: "2.0"
info:
  description: Swagger doc for /api/sys/firmware_info_pim
  title: Swagger doc for /api/sys/firmware_info_pim
  version: 1.0.0
paths:
  /api/sys/firmware_info_pim:
    get:
      produces: [application/json]
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Resources:
                type: array
                items:
                  type: string
              Actions:
                type: array
                items:
                  type: string
              Information:
                type: object
                additionalProperties: false
                properties:
                  "1":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
                  "2":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
                  "3":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
                  "4":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
                  "5":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
                  "6":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
                  "7":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
                  "8":
                    type: string
                    pattern: "^[0-9]+[.][0-9]+$"
