swagger: "2.0"
info:
  description: Swagger doc for /api/sys/gpios
  title: Swagger doc for /api/sys/gpios
  version: 1.0.0
paths:
  /api/sys/gpios:
    get:
      produces: [application/json]
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              back_ports:
                port_1:
                  type: object
                  additionalProperties: false
                  pin_1:
                    type: number
                  pin_2:
                    type: number
                  pin_3:
                    type: number
                  pin_4:
                    type: number
                port_2:
                  type: object
                  additionalProperties: false
                  pin_1:
                    type: number
                  pin_2:
                    type: number
                  pin_3:
                    type: number
                  pin_4:
                    type: number
