swagger: "2.0"
info:
  description: Swagger doc for /api/sys/gpios
  title: Swagger doc for /api/sys/gpios
  version: 1.0.0
paths:
  /api/sys/gpios:
    get:
      produces: [application/json]
      responses:
        200:
          description: ok
          schema:
            type: object
            maxProperties: 0
